// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxIg6LgIZVrvyHWQDWTL9fpRymfxLTOLs',
    appId: '1:644887327998:web:24b02c1d6dc05eca8d21af',
    messagingSenderId: '644887327998',
    projectId: 'mockinterview-hirecraft',
    authDomain: 'mockinterview-hirecraft.firebaseapp.com',
    storageBucket: 'mockinterview-hirecraft.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGgXKdgCo9WPtuH2_rmVBMTYq5pFQfV2Q',
    appId: '1:644887327998:android:18a42704712ea6688d21af',
    messagingSenderId: '644887327998',
    projectId: 'mockinterview-hirecraft',
    storageBucket: 'mockinterview-hirecraft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTqx_aEC9nxunEopJ8_VDqeaWexMgavDY',
    appId: '1:644887327998:ios:6ea95abc85fa065b8d21af',
    messagingSenderId: '644887327998',
    projectId: 'mockinterview-hirecraft',
    storageBucket: 'mockinterview-hirecraft.firebasestorage.app',
    iosBundleId: 'com.example.mockinterviewapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTqx_aEC9nxunEopJ8_VDqeaWexMgavDY',
    appId: '1:644887327998:ios:6ea95abc85fa065b8d21af',
    messagingSenderId: '644887327998',
    projectId: 'mockinterview-hirecraft',
    storageBucket: 'mockinterview-hirecraft.firebasestorage.app',
    iosBundleId: 'com.example.mockinterviewapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxIg6LgIZVrvyHWQDWTL9fpRymfxLTOLs',
    appId: '1:644887327998:web:421b970f5ef7f33d8d21af',
    messagingSenderId: '644887327998',
    projectId: 'mockinterview-hirecraft',
    authDomain: 'mockinterview-hirecraft.firebaseapp.com',
    storageBucket: 'mockinterview-hirecraft.firebasestorage.app',
  );
}
